project:
  type: website

website:
  site-url: https://jeannefrancojra.quarto.pub
  google-analytics:
    tracking-id: "G-DPJZ1QC6J5"
  open-graph: true
  favicon: trevo.png
  page-footer:
    left: "Blog feito com 🖤 e [Quarto](https://quarto.org/), por Jeanne Franco."
    right: 
      - icon: github
        href: https://github.com/francojra
      - icon: instagram
        href: https://www.instagram.com/jeanneefranco/
      - icon: youtube
        href: https://www.youtube.com/channel/UCValiiCyO82tJmG0BXnQuow
      - icon: linkedin
        href: https://www.linkedin.com/in/francojra/
      - icon: envelope
        href: mailto:jeanneraquelj1@gmail.com
        
  page-navigation: true
  title: "Jeanne Franco"
  navbar:
    right:
      - text: Postagens
        menu: 
          - index.qmd
          - divulgacao-cientifica.qmd
      - text: Atividades
        menu:
          - beta_analitica.qmd
          - rladies.qmd
          - servicos.qmd
          - palestras.qmd
      - text: Sobre
        menu: 
          - about.qmd
          - formacao.qmd
      - contact.qmd

format:
  html:
    theme: sketchy
      #light: [pulse,custom.scss] # Tema modo claro
      #dark:  [cyborg,custom.scss] # Tema modo escuro
    css: styles.css
    link-external-newwindow: true
    toc: true

editor: visual

comments:
  giscus:
    repo: francojra/meu_blog_com_quarto
    language: pt
    mapping: title
    theme: dark_high_contrast
    
