project:
  type: website

website:
  google-analytics: "G-2J79YYG9CZ"
  page-footer:
    left: "Blog made with [Quarto](https://quarto.org/), by Jeanne Franco.
    title: "Jeanne Franco"
    navbar:
    right:
      - index.qmd
      - about.qmd
      - formacao.qmd
      - icon: github
        href: https://github.com/francojra
      - icon: instagram
        href: https://www.instagram.com/jeanneefranco/
      - icon: twitter
        href: https://twitter.com/JeanneF06042346
      - icon: youtube
        href: https://www.youtube.com/channel/UCValiiCyO82tJmG0BXnQuow
      - icon: linkedin
        href: https://www.linkedin.com/in/francojra/
      - icon: envelope
        href: mailto:jeanne.raquel02@hotmail.com
format:
  html:
    theme: sketchy
    css: styles.css

editor: visual

