project:
  type: website

website:
  title: "Página Inicial"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/francojra
      - icon: twitter
        href: https://twitter.com/JeanneF06042346
      - icon: envelope
        href: mailto:jeanne.raquel02@hotmail.com
      - icon: linkedin
        href: https://www.linkedin.com/in/francojra/
      - icon: instagram
        href: https://www.instagram.com/jeanneefranco/
      - icon: youtube
        href: https://www.youtube.com/channel/UCValiiCyO82tJmG0BXnQuow
format:
  html:
    theme: sketchy
    css: styles.css

editor: visual

