---
title: "Nova geração de jovens consome menos álcool"
author: "Jeanne Franco"
date: "08-27-2023"
categories: [Sociedade]
lang: pt
---

## Queda no consumo de álcool

Estudos realizados em vários países do mundo observaram tendências no menor consumo de álcool pela atual geração de jovens.

Um levantamento feito em 2020 com jovens entre 12 e 18 anos, idade em que a maioria experimenta álcool pela primeira vez, observou queda no consumo de bebidas alcoólicas em 39 países da América do Norte, Europa e Oceania. Comparado há 20 anos atrás, a redução chega a 50% em países como Noruega, Suécia e Lituânia, e chega a um percentual surpreendente de 80% na Islândia.

A organização britânica Drinkaware relatou que 26% dos jovens entre 16 e 24 anos se consideram abstêmios, ou seja, que não fazem uso de álcool ou consomem muito pouco.

No Brasil, um levantamento feito em 2021 verificou que apenas 19,3% dos jovens entre 18 e 24 anos fazem consumo abusivo de álcool com mais de quatro doses. Essa porcentagem foi a mais baixa desde 2015.

Já uma pesquisa publicada pelo Centro de Informações sobre Saúde e Álcool (Cisa) cosntatou que 46% dos jovens afirma não consumirem álcool, e 20% afirma consumir apenas uma vez por mês ou menos. Comparado a outras idades, adolescentes e jovens adultos apresentam a menor frequência de consumo. Entretanto, o Cisa menciona que ainda não existem dados suficientes para confirmar a tendência na redução do consumo.

## Razões

As principais motivações dos jovens atualmente para não consumir bebidas alcoólicas são: reputação e bom desempenho nas atividades rotineiras e no trabalho. Fatores como reuniões familiares, confraternizações com colegas de trabalho e necessidade de dirigir também influenciam em atitudes mais comedidas quanto ao álcool.




