---
title: "Estatística descritiva com base de dados do Kaggle"
author: "Jeanne Franco"
format: html 
# format: pdf
date: 04/16/23
categories: [Códigos, Estatística, packages, R]
lang: pt
toc: true
---

A estatística descritiva é um etapa inicial e importante para você entender os seus dados. Ao utilizar algumas funções e pacotes que ajudam a descrever os dados, nós podemos saber a quantidade de linhas e colunas da tabela, a quantidade de variáveis numéricas discretas (números inteiros) e contínuas (valores quabrados ou infinitos), quantidade de variáveis categóricas, dados faltantes e número total de observações.

A estatística descritiva básica nos permite fazer um resumo dos nossos dados para avaliar a frequência da distribuição de variáveis numéricas através de histogramas, identificar as médias, medianas, valores máximos e mínimos, desvios e erros padrão, além de fazer correlações entre variáveis.

Para fazer essas análises de forma rápida e eficiente, podemos usar o pacote `DataExplorer` disponível para instalar no R, o qual gera um relatório completo em PDF ou HTML da análise exploratória dos seus dados.

FALAR ONDE ENCONTRAR A BASE DE DADOS DO KAGGLE E COLOCAR O LINK
