---
title: "Modelagem de Equações Estruturais"
author: "Jeanne Franco"
format: html
editor: visual
date: 09/04/2013
---

## Equações Estruturais em R: Conceitos e Aplicações Práticas

As Equações Estruturais são uma técnica estatística avançada usada para modelar relações complexas entre variáveis observadas e latentes. Elas combinam aspectos da análise fatorial e da regressão múltipla, permitindo que pesquisadores testem hipóteses sobre relações causais entre variáveis.

Neste post, vamos explorar como implementar modelos de equações estruturais em R usando o pacote `lavaan`. Além disso, vamos interpretar os resultados de um exemplo prático.

## O que são Equações Estruturais?

Equações estruturais são modelos que permitem analisar relações entre variáveis observadas (medidas diretamente como dados de altura, idade, peso, gênero, etc.) e variáveis latentes (não observadas diretamente, mas inferidas a partir de variáveis observadas como felicidade, ansiedade, depressão que podem ser medidas a partir de informações como níveis de cortisol, interação social, consultas a psicólogos, etc.). Esses modelos são úteis em áreas como psicologia, ciências sociais e marketing, onde muitas vezes trabalhamos com conceitos abstratos (como "satisfação do cliente" ou "inteligência emocional") que não podem ser medidos diretamente.

Um modelo de equações estruturais é composto por duas partes principais:

1.  **Modelo de Medida**: Relaciona as variáveis observadas às variáveis latentes.

2.  **Modelo Estrutural**: Define as relações entre as variáveis latentes.
